[package]
name = "gpt"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "gpt"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.14.0"
serde = "1.0.203"
serde_json = "1.0.117"


[dev-dependencies]
marine-rs-sdk-test = "0.16.1"
